apiVersion: v1
kind: Service
metadata:
  name: wisecow-deployment
spec:
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 4499
      nodePort: 31679   # External port on the node (you can choose any unused port)
  type: NodePort
