apiVersion: v1
kind: Service
metadata:
  name: wisecow-deployment
spec:
  selector:
    app: wisecow
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4499
      nodePort: 31679   # External port on the node (you can choose any unused port)
    - name: https
      protocol: TCP
      port: 443
      targetPort: 4499
      nodePort: 31680
  type: NodePort
